# Generated by Django 5.0.4 on 2024-04-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselorprofile',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='counselorprofile',
            name='bio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='counselorprofile',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
